blueprint:
  name: Optimal Battery Discharge for Off-Peak Slots (Dynamic Start with Grid Control)
  description: Discharge battery dynamically before off-peak slots based on calculated discharge time, with control for grid charging and discharging.
  domain: automation
  input:
    battery_charge_sensor:
      name: Battery Charge Sensor
      description: Sensor showing the battery's current charge as a percentage.
      selector:
        entity:
          domain: sensor

    energy_flow_sensor:
      name: Household Energy Consumption Sensor
      description: Sensor for household energy consumption (negative if solar is contributing).
      selector:
        entity:
          domain: sensor

    offpeak_binary_sensor:
      name: Off-Peak Schedule Sensor
      description: Binary sensor for off-peak slots (turns on when off-peak is active).
      selector:
        entity:
          domain: binary_sensor

    charge_switch:
      name: Charge from Grid Switch
      description: Switch to enable charging from the grid.
      selector:
        entity:
          domain: switch

    discharge_switch:
      name: Discharge to Grid Switch
      description: Switch to enable discharging to the grid.
      selector:
        entity:
          domain: switch

    inverter_capacity:
      name: Inverter Capacity (kW)
      description: Maximum inverter output capacity in kilowatts (e.g., 3.8).
      default: 3.8

    battery_capacity:
      name: Battery Capac
